---
title: "Run vs. Pass Offense"
output: 
  html_document:
    df_print: paged
---
```{r}

```

```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)

source("ShowSubsets.r")

COLLEGEPASSDATA2000 <- read_csv("COLLEGEDATA2000PASS.csv")

```

```{r}
mean(COLLEGEPASSDATA2000$RushAttOff, data=COLLEGEPASSDATA2000)
mean(COLLEGEPASSDATA2000$RushYdsOff, data=COLLEGEPASSDATA2000)
mean(COLLEGEPASSDATA2000$RushAvgOff, data=COLLEGEPASSDATA2000)
mean(COLLEGEPASSDATA2000$PassAttOff, data=COLLEGEPASSDATA2000)
mean(COLLEGEPASSDATA2000$PassYdsOff, data=COLLEGEPASSDATA2000)
mean(COLLEGEPASSDATA2000$PassYardsAttOff, data=COLLEGEPASSDATA2000)

```

```{r}

COLLEGEPASSDATA2001 <- read_csv("COLLEGEDATA2001PASS.csv")
```

```{r}
mean(COLLEGEPASSDATA2001$RushAttOff, data=COLLEGEPASSDATA2001)
mean(COLLEGEPASSDATA2001$RushYdsOff, data=COLLEGEPASSDATA2001)
mean(COLLEGEPASSDATA2001$RushAvgOff, data=COLLEGEPASSDATA2001)
mean(COLLEGEPASSDATA2001$PassAttOff, data=COLLEGEPASSDATA2001)
mean(COLLEGEPASSDATA2001$PassYdsOff, data=COLLEGEPASSDATA2001)
mean(COLLEGEPASSDATA2001$PassYardsAttOff, data=COLLEGEPASSDATA2001)

```

```{r}

COLLEGEPASSDATA2002 <- read_csv("COLLEGEDATA2002PASS.csv")
```

```{r}
mean(COLLEGEPASSDATA2002$RushAttOff, data=COLLEGEPASSDATA2002)
mean(COLLEGEPASSDATA2002$RushYdsOff, data=COLLEGEPASSDATA2002)
mean(COLLEGEPASSDATA2002$RushAvgOff, data=COLLEGEPASSDATA2002)
mean(COLLEGEPASSDATA2002$PassAttOff, data=COLLEGEPASSDATA2002)
mean(COLLEGEPASSDATA2002$PassYdsOff, data=COLLEGEPASSDATA2002)
mean(COLLEGEPASSDATA2002$PassYardsAttOff, data=COLLEGEPASSDATA2002)

```

```{r}

COLLEGEPASSDATA2003 <- read_csv("COLLEGEDATA2003PASS.csv")
```

```{r}
mean(COLLEGEPASSDATA2003$RushAttOff, data=COLLEGEPASSDATA2003)
mean(COLLEGEPASSDATA2003$RushYdsOff, data=COLLEGEPASSDATA2003)
mean(COLLEGEPASSDATA2003$RushAvgOff, data=COLLEGEPASSDATA2003)
mean(COLLEGEPASSDATA2003$PassAttOff, data=COLLEGEPASSDATA2003)
mean(COLLEGEPASSDATA2003$PassYdsOff, data=COLLEGEPASSDATA2003)
mean(COLLEGEPASSDATA2003$PassYardsAttOff, data=COLLEGEPASSDATA2003)

```

```{r}

COLLEGEPASSDATA2004 <- read_csv("COLLEGEDATA2004PASS.csv")
```

```{r}
mean(COLLEGEPASSDATA2004$RushAttOff, data=COLLEGEPASSDATA2004)
mean(COLLEGEPASSDATA2004$RushYdsOff, data=COLLEGEPASSDATA2004)
mean(COLLEGEPASSDATA2004$RushAvgOff, data=COLLEGEPASSDATA2004)
mean(COLLEGEPASSDATA2004$PassAttOff, data=COLLEGEPASSDATA2004)
mean(COLLEGEPASSDATA2004$PassYdsOff, data=COLLEGEPASSDATA2004)
mean(COLLEGEPASSDATA2004$PassYardsAttOff, data=COLLEGEPASSDATA2004)

```

```{r}

COLLEGEPASSDATA2005 <- read_csv("COLLEGEDATA2005PASS.csv")
```

```{r}
mean(COLLEGEPASSDATA2005$RushAttOff, data=COLLEGEPASSDATA2005)
mean(COLLEGEPASSDATA2005$RushYdsOff, data=COLLEGEPASSDATA2005)
mean(COLLEGEPASSDATA2005$RushAvgOff, data=COLLEGEPASSDATA2005)
mean(COLLEGEPASSDATA2005$PassAttOff, data=COLLEGEPASSDATA2005)
mean(COLLEGEPASSDATA2005$PassYdsOff, data=COLLEGEPASSDATA2005)
mean(COLLEGEPASSDATA2005$PassYardsAttOff, data=COLLEGEPASSDATA2005)

```

```{r}

COLLEGEPASSDATA2006 <- read_csv("COLLEGEDATA2006PASS.csv")
```

```{r}
mean(COLLEGEPASSDATA2006$RushAttOff, data=COLLEGEPASSDATA2006)
mean(COLLEGEPASSDATA2006$RushYdsOff, data=COLLEGEPASSDATA2006)
mean(COLLEGEPASSDATA2006$RushAvgOff, data=COLLEGEPASSDATA2006)
mean(COLLEGEPASSDATA2006$PassAttOff, data=COLLEGEPASSDATA2006)
mean(COLLEGEPASSDATA2006$PassYdsOff, data=COLLEGEPASSDATA2006)
mean(COLLEGEPASSDATA2006$PassYardsAttOff, data=COLLEGEPASSDATA2006)

```

```{r}

COLLEGEPASSDATA2007 <- read_csv("COLLEGEDATA2007PASS.csv")
```

```{r}
mean(COLLEGEPASSDATA2007$RushAttOff, data=COLLEGEPASSDATA2007)
mean(COLLEGEPASSDATA2007$RushYdsOff, data=COLLEGEPASSDATA2007)
mean(COLLEGEPASSDATA2007$RushAvgOff, data=COLLEGEPASSDATA2007)
mean(COLLEGEPASSDATA2007$PassAttOff, data=COLLEGEPASSDATA2007)
mean(COLLEGEPASSDATA2007$PassYdsOff, data=COLLEGEPASSDATA2007)
mean(COLLEGEPASSDATA2007$PassYardsAttOff, data=COLLEGEPASSDATA2007)

```

```{r}

COLLEGEPASSDATA2008 <- read_csv("COLLEGEDATA2008PASS.csv")
```

```{r}
mean(COLLEGEPASSDATA2008$RushAttOff, data=COLLEGEPASSDATA2008)
mean(COLLEGEPASSDATA2008$RushYdsOff, data=COLLEGEPASSDATA2008)
mean(COLLEGEPASSDATA2008$RushAvgOff, data=COLLEGEPASSDATA2008)
mean(COLLEGEPASSDATA2008$PassAttOff, data=COLLEGEPASSDATA2008)
mean(COLLEGEPASSDATA2008$PassYdsOff, data=COLLEGEPASSDATA2008)
mean(COLLEGEPASSDATA2008$PassYardsAttOff, data=COLLEGEPASSDATA2008)

```

```{r}

COLLEGEPASSDATA2009 <- read_csv("COLLEGEDATA2009PASS.csv")
```

```{r}
mean(COLLEGEPASSDATA2009$RushAttOff, data=COLLEGEPASSDATA2009)
mean(COLLEGEPASSDATA2009$RushYdsOff, data=COLLEGEPASSDATA2009)
mean(COLLEGEPASSDATA2009$RushAvgOff, data=COLLEGEPASSDATA2009)
mean(COLLEGEPASSDATA2009$PassAttOff, data=COLLEGEPASSDATA2009)
mean(COLLEGEPASSDATA2009$PassYdsOff, data=COLLEGEPASSDATA2009)
mean(COLLEGEPASSDATA2009$PassYardsAttOff, data=COLLEGEPASSDATA2009)

```

```{r}

COLLEGEPASSDATA2010 <- read_csv("COLLEGEDATA2010PASS.csv")
```

```{r}
mean(COLLEGEPASSDATA2010$RushAttOff, data=COLLEGEPASSDATA2010)
mean(COLLEGEPASSDATA2010$RushYdsOff, data=COLLEGEPASSDATA2010)
mean(COLLEGEPASSDATA2010$RushAvgOff, data=COLLEGEPASSDATA2010)
mean(COLLEGEPASSDATA2010$PassAttOff, data=COLLEGEPASSDATA2010)
mean(COLLEGEPASSDATA2010$PassYdsOff, data=COLLEGEPASSDATA2010)
mean(COLLEGEPASSDATA2010$PassYardsAttOff, data=COLLEGEPASSDATA2010)

```

```{r}

COLLEGEPASSDATA2011 <- read_csv("COLLEGEDATA2011PASS.csv")
```

```{r}
mean(COLLEGEPASSDATA2011$RushAttOff, data=COLLEGEPASSDATA2011)
mean(COLLEGEPASSDATA2011$RushYdsOff, data=COLLEGEPASSDATA2011)
mean(COLLEGEPASSDATA2011$RushAvgOff, data=COLLEGEPASSDATA2011)
mean(COLLEGEPASSDATA2011$PassAttOff, data=COLLEGEPASSDATA2011)
mean(COLLEGEPASSDATA2011$PassYdsOff, data=COLLEGEPASSDATA2011)
mean(COLLEGEPASSDATA2011$PassYardsAttOff, data=COLLEGEPASSDATA2011)

```

```{r}

COLLEGEPASSDATA2012 <- read_csv("COLLEGEDATA2012PASS.csv")
head(COLLEGEPASSDATA2012)
```

```{r}
mean(COLLEGEPASSDATA2012$RushAttOff, data=COLLEGEPASSDATA2012)
mean(COLLEGEPASSDATA2012$RushYdsOff, data=COLLEGEPASSDATA2012)
mean(COLLEGEPASSDATA2012$RushAvgOff, data=COLLEGEPASSDATA2012)
mean(COLLEGEPASSDATA2012$PassAttOff, data=COLLEGEPASSDATA2012)
mean(COLLEGEPASSDATA2012$PassYdsOff, data=COLLEGEPASSDATA2012)
mean(COLLEGEPASSDATA2012$PassYardsAttOff, data=COLLEGEPASSDATA2012)

```

```{r}

COLLEGEPASSDATA2013 <- read_csv("COLLEGEDATA2013PASS.csv")
```

```{r}
mean(COLLEGEPASSDATA2013$RushAttOff, data=COLLEGEPASSDATA2013)
mean(COLLEGEPASSDATA2013$RushYdsOff, data=COLLEGEPASSDATA2013)
mean(COLLEGEPASSDATA2013$RushAvgOff, data=COLLEGEPASSDATA2013)
mean(COLLEGEPASSDATA2013$PassAttOff, data=COLLEGEPASSDATA2013)
mean(COLLEGEPASSDATA2013$PassYdsOff, data=COLLEGEPASSDATA2013)
mean(COLLEGEPASSDATA2013$PassYardsAttOff, data=COLLEGEPASSDATA2013)

```
