---
title: "Run vs. Pass Offense"
output: 
  html_document:
    df_print: paged
---
```{r}

```

```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)

source("ShowSubsets.r")

NFLPASSDATA2000 <- read_csv("NFLDATA2000PASS.csv")

```

```{r}
mean(NFLPASSDATA2000$RushAttOff, data=NFLPASSDATA2000)
mean(NFLPASSDATA2000$RushYdsOff, data=NFLPASSDATA2000)
mean(NFLPASSDATA2000$RushAvgOff, data=NFLPASSDATA2000)
mean(NFLPASSDATA2000$PassAttOff, data=NFLPASSDATA2000)
mean(NFLPASSDATA2000$PassYdsOff, data=NFLPASSDATA2000)
mean(NFLPASSDATA2000$PassYardsAttOff, data=NFLPASSDATA2000)

```

```{r}

NFLPASSDATA2001 <- read_csv("NFLDATA2001PASS.csv")
```

```{r}
mean(NFLPASSDATA2001$RushAttOff, data=NFLPASSDATA2001)
mean(NFLPASSDATA2001$RushYdsOff, data=NFLPASSDATA2001)
mean(NFLPASSDATA2001$RushAvgOff, data=NFLPASSDATA2001)
mean(NFLPASSDATA2001$PassAttOff, data=NFLPASSDATA2001)
mean(NFLPASSDATA2001$PassYdsOff, data=NFLPASSDATA2001)
mean(NFLPASSDATA2001$PassYardsAttOff, data=NFLPASSDATA2001)

```

```{r}

NFLPASSDATA2002 <- read_csv("NFLDATA2002PASS.csv")
```

```{r}
mean(NFLPASSDATA2002$RushAttOff, data=NFLPASSDATA2002)
mean(NFLPASSDATA2002$RushYdsOff, data=NFLPASSDATA2002)
mean(NFLPASSDATA2002$RushAvgOff, data=NFLPASSDATA2002)
mean(NFLPASSDATA2002$PassAttOff, data=NFLPASSDATA2002)
mean(NFLPASSDATA2002$PassYdsOff, data=NFLPASSDATA2002)
mean(NFLPASSDATA2002$PassYardsAttOff, data=NFLPASSDATA2002)

```

```{r}

NFLPASSDATA2003 <- read_csv("NFLDATA2003PASS.csv")
```

```{r}
mean(NFLPASSDATA2003$RushAttOff, data=NFLPASSDATA2003)
mean(NFLPASSDATA2003$RushYdsOff, data=NFLPASSDATA2003)
mean(NFLPASSDATA2003$RushAvgOff, data=NFLPASSDATA2003)
mean(NFLPASSDATA2003$PassAttOff, data=NFLPASSDATA2003)
mean(NFLPASSDATA2003$PassYdsOff, data=NFLPASSDATA2003)
mean(NFLPASSDATA2003$PassYardsAttOff, data=NFLPASSDATA2003)

```

```{r}

NFLPASSDATA2004 <- read_csv("NFLDATA2004PASS.csv")
```

```{r}
mean(NFLPASSDATA2004$RushAttOff, data=NFLPASSDATA2004)
mean(NFLPASSDATA2004$RushYdsOff, data=NFLPASSDATA2004)
mean(NFLPASSDATA2004$RushAvgOff, data=NFLPASSDATA2004)
mean(NFLPASSDATA2004$PassAttOff, data=NFLPASSDATA2004)
mean(NFLPASSDATA2004$PassYdsOff, data=NFLPASSDATA2004)
mean(NFLPASSDATA2004$PassYardsAttOff, data=NFLPASSDATA2004)

```

```{r}

NFLPASSDATA2005 <- read_csv("NFLDATA2005PASS.csv")
```

```{r}
mean(NFLPASSDATA2005$RushAttOff, data=NFLPASSDATA2005)
mean(NFLPASSDATA2005$RushYdsOff, data=NFLPASSDATA2005)
mean(NFLPASSDATA2005$RushAvgOff, data=NFLPASSDATA2005)
mean(NFLPASSDATA2005$PassAttOff, data=NFLPASSDATA2005)
mean(NFLPASSDATA2005$PassYdsOff, data=NFLPASSDATA2005)
mean(NFLPASSDATA2005$PassYardsAttOff, data=NFLPASSDATA2005)

```

```{r}

NFLPASSDATA2006 <- read_csv("NFLDATA2006PASS.csv")
```

```{r}
mean(NFLPASSDATA2006$RushAttOff, data=NFLPASSDATA2006)
mean(NFLPASSDATA2006$RushYdsOff, data=NFLPASSDATA2006)
mean(NFLPASSDATA2006$RushAvgOff, data=NFLPASSDATA2006)
mean(NFLPASSDATA2006$PassAttOff, data=NFLPASSDATA2006)
mean(NFLPASSDATA2006$PassYdsOff, data=NFLPASSDATA2006)
mean(NFLPASSDATA2006$PassYardsAttOff, data=NFLPASSDATA2006)

```

```{r}

NFLPASSDATA2007 <- read_csv("NFLDATA2007PASS.csv")
```

```{r}
mean(NFLPASSDATA2007$RushAttOff, data=NFLPASSDATA2007)
mean(NFLPASSDATA2007$RushYdsOff, data=NFLPASSDATA2007)
mean(NFLPASSDATA2007$RushAvgOff, data=NFLPASSDATA2007)
mean(NFLPASSDATA2007$PassAttOff, data=NFLPASSDATA2007)
mean(NFLPASSDATA2007$PassYdsOff, data=NFLPASSDATA2007)
mean(NFLPASSDATA2007$PassYardsAttOff, data=NFLPASSDATA2007)

```

```{r}

NFLPASSDATA2008 <- read_csv("NFLDATA2008PASS.csv")
```

```{r}
mean(NFLPASSDATA2008$RushAttOff, data=NFLPASSDATA2008)
mean(NFLPASSDATA2008$RushYdsOff, data=NFLPASSDATA2008)
mean(NFLPASSDATA2008$RushAvgOff, data=NFLPASSDATA2008)
mean(NFLPASSDATA2008$PassAttOff, data=NFLPASSDATA2008)
mean(NFLPASSDATA2008$PassYdsOff, data=NFLPASSDATA2008)
mean(NFLPASSDATA2008$PassYardsAttOff, data=NFLPASSDATA2008)

```

```{r}

NFLPASSDATA2009 <- read_csv("NFLDATA2009PASS.csv")
```

```{r}
mean(NFLPASSDATA2009$RushAttOff, data=NFLPASSDATA2009)
mean(NFLPASSDATA2009$RushYdsOff, data=NFLPASSDATA2009)
mean(NFLPASSDATA2009$RushAvgOff, data=NFLPASSDATA2009)
mean(NFLPASSDATA2009$PassAttOff, data=NFLPASSDATA2009)
mean(NFLPASSDATA2009$PassYdsOff, data=NFLPASSDATA2009)
mean(NFLPASSDATA2009$PassYardsAttOff, data=NFLPASSDATA2009)

```

```{r}

NFLPASSDATA2010 <- read_csv("NFLDATA2010PASS.csv")
```

```{r}
mean(NFLPASSDATA2010$RushAttOff, data=NFLPASSDATA2010)
mean(NFLPASSDATA2010$RushYdsOff, data=NFLPASSDATA2010)
mean(NFLPASSDATA2010$RushAvgOff, data=NFLPASSDATA2010)
mean(NFLPASSDATA2010$PassAttOff, data=NFLPASSDATA2010)
mean(NFLPASSDATA2010$PassYdsOff, data=NFLPASSDATA2010)
mean(NFLPASSDATA2010$PassYardsAttOff, data=NFLPASSDATA2010)

```

```{r}

NFLPASSDATA2011 <- read_csv("NFLDATA2011PASS.csv")
```

```{r}
mean(NFLPASSDATA2011$RushAttOff, data=NFLPASSDATA2011)
mean(NFLPASSDATA2011$RushYdsOff, data=NFLPASSDATA2011)
mean(NFLPASSDATA2011$RushAvgOff, data=NFLPASSDATA2011)
mean(NFLPASSDATA2011$PassAttOff, data=NFLPASSDATA2011)
mean(NFLPASSDATA2011$PassYdsOff, data=NFLPASSDATA2011)
mean(NFLPASSDATA2011$PassYardsAttOff, data=NFLPASSDATA2011)

```

```{r}

NFLPASSDATA2012 <- read_csv("NFLDATA2012PASS.csv")
```

```{r}
mean(NFLPASSDATA2012$RushAttOff, data=NFLPASSDATA2012)
mean(NFLPASSDATA2012$RushYdsOff, data=NFLPASSDATA2012)
mean(NFLPASSDATA2012$RushAvgOff, data=NFLPASSDATA2012)
mean(NFLPASSDATA2012$PassAttOff, data=NFLPASSDATA2012)
mean(NFLPASSDATA2012$PassYdsOff, data=NFLPASSDATA2012)
mean(NFLPASSDATA2012$PassYardsAttOff, data=NFLPASSDATA2012)

```

```{r}

NFLPASSDATA2013 <- read_csv("NFLDATA2013PASS.csv")
```

```{r}
mean(NFLPASSDATA2013$RushAttOff, data=NFLPASSDATA2013)
mean(NFLPASSDATA2013$RushYdsOff, data=NFLPASSDATA2013)
mean(NFLPASSDATA2013$RushAvgOff, data=NFLPASSDATA2013)
mean(NFLPASSDATA2013$PassAttOff, data=NFLPASSDATA2013)
mean(NFLPASSDATA2013$PassYdsOff, data=NFLPASSDATA2013)
mean(NFLPASSDATA2013$PassYardsAttOff, data=NFLPASSDATA2013)

```
