---
title: "Predicting Score Differentials - CDC 2020"
output: 
  html_document:
    df_print: paged
---
```{r}

```

```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)


NFLDATA2000 <- read_csv("NFL2000DATA.csv")
source("ShowSubsets.R")

```

```{r}
all2000 = regsubsets(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2000, nbest = 2, nvmax = 25)

ShowSubsetsTable = ShowSubsets(all2000)
head(arrange(ShowSubsetsTable, Cp))

```

```{r}
Full2000 = lm(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2000)
MSE = (summary(Full2000)$sigma)^2
step(Full2000, scale=MSE, trace = FALSE)

```

```{r}
none2000 = lm(ScoreDiff~1, data=NFLDATA2000)
step(none2000, scope=list(upper=Full2000), scale=MSE, direction="forward", trace = FALSE)
```

```{r}
step(none2000, scope=list(upper=Full2000), scale=MSE, trace = FALSE)
```

```{r}
summary(Full2000)
```

```{r}
plot(Full2000)
```

```{r}
plot(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2000)
```


```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)


NFLDATA2001 <- read_csv("NFLDATA2001.csv")
source("ShowSubsets.R")

```

```{r}
all2001 = regsubsets(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2001, nbest = 2, nvmax = 25)

ShowSubsetsTable = ShowSubsets(all2001)
head(arrange(ShowSubsetsTable, Cp))

```

```{r}
Full2001 = lm(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2001)

MSE = (summary(Full2001)$sigma)^2
step(Full2001, scale=MSE, trace = FALSE)
```

```{r}
none2001 = lm(ScoreDiff~1, data=NFLDATA2001)
step(none2001, scope=list(upper=Full2001), scale=MSE, direction="forward", trace = FALSE)
```

```{r}
step(none2001, scope=list(upper=Full2001), scale=MSE, trace = FALSE)
```

```{r}
summary(Full2001)
```

```{r}
plot(Full2001)
```

```{r}
plot(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2001)
```


```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)


NFLDATA2002 <- read_csv("NFLDATA2002.csv")
source("ShowSubsets.R")

```

```{r}
all2002 = regsubsets(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2002, nbest = 2, nvmax = 25)

ShowSubsetsTable = ShowSubsets(all2002)
head(arrange(ShowSubsetsTable, Cp))

```

```{r}
Full2002 = lm(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2002)
MSE = (summary(Full2002)$sigma)^2
step(Full2002, scale=MSE, trace = FALSE)
```

```{r}
none2002 = lm(ScoreDiff~1, data=NFLDATA2002)
step(none2002, scope=list(upper=Full2002), scale=MSE, direction="forward", trace = FALSE)
```

```{r}
step(none2002, scope=list(upper=Full2002), scale=MSE, trace = FALSE)
```

```{r}
summary(Full2002)
```

```{r}
plot(Full2002)
```

```{r}
plot(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2002)
```


```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)


NFLDATA2003 <- read_csv("NFLDATA2003.csv")
source("ShowSubsets.R")

```

```{r}
all2003 = regsubsets(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2003, nbest = 2, nvmax = 25)

ShowSubsetsTable = ShowSubsets(all2003)
head(arrange(ShowSubsetsTable, Cp))

```

```{r}
Full2003 = lm(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2003)
MSE = (summary(Full2003)$sigma)^2
step(Full2003, scale=MSE, trace = FALSE)
```

```{r}
none2003 = lm(ScoreDiff~1, data=NFLDATA2003)
step(none2003, scope=list(upper=Full2003), scale=MSE, direction="forward", trace = FALSE)
```

```{r}
step(none2003, scope=list(upper=Full2003), scale=MSE, trace = FALSE)
```

```{r}
summary(Full2003)
```

```{r}
plot(Full2003)
```

```{r}
plot(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2003)
```



```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)


NFLDATA2004 <- read_csv("NFLDATA2004.csv")
source("ShowSubsets.R")

```

```{r}
all2004 = regsubsets(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2004, nbest = 2, nvmax = 25)

ShowSubsetsTable = ShowSubsets(all2004)
head(arrange(ShowSubsetsTable, Cp))

```

```{r}
Full2004 = lm(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2004)
MSE = (summary(Full2004)$sigma)^2
step(Full2004, scale=MSE, trace = FALSE)
```

```{r}
none2004 = lm(ScoreDiff~1, data=NFLDATA2004)
step(none2004, scope=list(upper=Full2004), scale=MSE, direction="forward", trace = FALSE)
```

```{r}
step(none2004, scope=list(upper=Full2004), scale=MSE, trace = FALSE)
```

```{r}
summary(Full2004)
```

```{r}
plot(Full2004)
```

```{r}
plot(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2004)
```


```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)


NFLDATA2005 <- read_csv("NFLDATA2005.csv")
source("ShowSubsets.R")

```

```{r}
all2005 = regsubsets(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2005, nbest = 2, nvmax = 25)

ShowSubsetsTable = ShowSubsets(all2005)
head(arrange(ShowSubsetsTable, Cp))

```

```{r}
Full2005 = lm(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2005)
MSE = (summary(Full2005)$sigma)^2
step(Full2005, scale=MSE, trace = FALSE)
```

```{r}
none2005 = lm(ScoreDiff~1, data=NFLDATA2005)
step(none2005, scope=list(upper=Full2005), scale=MSE, direction="forward", trace = FALSE)
```

```{r}
step(none2005, scope=list(upper=Full2005), scale=MSE, trace = FALSE)
```

```{r}
summary(Full2005)
```

```{r}
plot(Full2005)
```

```{r}
plot(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2005)
```


```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)


NFLDATA2006 <- read_csv("NFLDATA2006.csv")
source("ShowSubsets.R")

```

```{r}
all2006 = regsubsets(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2006, nbest = 2, nvmax = 25)

ShowSubsetsTable = ShowSubsets(all2006)
head(arrange(ShowSubsetsTable, Cp))

```

```{r}
Full2006 = lm(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2006)
MSE = (summary(Full2006)$sigma)^2
step(Full2006, scale=MSE, trace = FALSE)
```

```{r}
none2006 = lm(ScoreDiff~1, data=NFLDATA2006)
step(none2006, scope=list(upper=Full2006), scale=MSE, direction="forward", trace = FALSE)
```

```{r}
step(none2006, scope=list(upper=Full2006), scale=MSE, trace = FALSE)
```

```{r}
summary(Full2006)
```

```{r}
plot(Full2006)
```

```{r}
plot(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2006)
```


```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)


NFLDATA2007 <- read_csv("NFLDATA2007.csv")
source("ShowSubsets.R")

```

```{r}
all2007 = regsubsets(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2007, nbest = 2, nvmax = 25)

ShowSubsetsTable = ShowSubsets(all2007)
head(arrange(ShowSubsetsTable, Cp))

```

```{r}
Full2007 = lm(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2007)
MSE = (summary(Full2007)$sigma)^2
step(Full2007, scale=MSE, trace = FALSE)
```

```{r}
none2007 = lm(ScoreDiff~1, data=NFLDATA2007)
step(none2007, scope=list(upper=Full2007), scale=MSE, direction="forward", trace = FALSE)
```

```{r}
step(none2007, scope=list(upper=Full2007), scale=MSE, trace = FALSE)
```

```{r}
summary(Full2007)
```

```{r}
plot(Full2007)
```

```{r}
plot(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2007)
```


```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)


NFLDATA2008 <- read_csv("NFLDATA2008.csv")
source("ShowSubsets.R")

```

```{r}
all2008 = regsubsets(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2008, nbest = 2, nvmax = 25)

ShowSubsetsTable = ShowSubsets(all2008)
head(arrange(ShowSubsetsTable, Cp))

```

```{r}
Full2008 = lm(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2008)
MSE = (summary(Full2008)$sigma)^2
step(Full2008, scale=MSE, trace = FALSE)
```

```{r}
none2008 = lm(ScoreDiff~1, data=NFLDATA2008)
step(none2008, scope=list(upper=Full2008), scale=MSE, direction="forward", trace = FALSE)
```

```{r}
step(none2008, scope=list(upper=Full2008), scale=MSE, trace = FALSE)
```

```{r}
summary(Full2008)
```

```{r}
plot(Full2008)
```

```{r}
plot(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2008)
```


```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)


NFLDATA2009 <- read_csv("NFLDATA2009.csv")
source("ShowSubsets.R")

```

```{r}
all2009 = regsubsets(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2009, nbest = 2, nvmax = 25)

ShowSubsetsTable = ShowSubsets(all2009)
head(arrange(ShowSubsetsTable, Cp))

```

```{r}
Full2009 = lm(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2009)
MSE = (summary(Full2009)$sigma)^2
step(Full2009, scale=MSE, trace = FALSE)
```

```{r}
none2009 = lm(ScoreDiff~1, data=NFLDATA2009)
step(none2009, scope=list(upper=Full2009), scale=MSE, direction="forward", trace = FALSE)
```

```{r}
step(none2009, scope=list(upper=Full2009), scale=MSE, trace = FALSE)
```

```{r}
summary(Full2009)
```

```{r}
plot(Full2009)
```

```{r}
plot(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2009)
```


```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)


NFLDATA2010 <- read_csv("NFLDATA2010.csv")
source("ShowSubsets.R")

```

```{r}
all2010 = regsubsets(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2010, nbest = 2, nvmax = 25)

ShowSubsetsTable = ShowSubsets(all2010)
head(arrange(ShowSubsetsTable, Cp))

```

```{r}
Full2010 = lm(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2010)
MSE = (summary(Full2010)$sigma)^2
step(Full2010, scale=MSE, trace = FALSE)
```

```{r}
none2010 = lm(ScoreDiff~1, data=NFLDATA2010)
step(none2010, scope=list(upper=Full2010), scale=MSE, direction="forward", trace = FALSE)
```

```{r}
step(none2010, scope=list(upper=Full2010), scale=MSE, trace = FALSE)
```

```{r}
summary(Full2010)
```

```{r}
plot(Full2010)
```

```{r}
plot(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2010)
```


```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)


NFLDATA2011 <- read_csv("NFLDATA2011.csv")
source("ShowSubsets.R")

```

```{r}
all2011 = regsubsets(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2011, nbest = 2, nvmax = 25)

ShowSubsetsTable = ShowSubsets(all2011)
head(arrange(ShowSubsetsTable, Cp))

```

```{r}
Full2011 = lm(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2011)
MSE = (summary(Full2011)$sigma)^2
step(Full2011, scale=MSE, trace = FALSE)
```

```{r}
none2011 = lm(ScoreDiff~1, data=NFLDATA2011)
step(none2011, scope=list(upper=Full2011), scale=MSE, direction="forward", trace = FALSE)
```

```{r}
step(none2011, scope=list(upper=Full2011), scale=MSE, trace = FALSE)
```

```{r}
summary(Full2011)
```

```{r}
plot(Full2011)
```

```{r}
plot(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2011)
```


```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)


NFLDATA2012 <- read_csv("NFLDATA2012.csv")
source("ShowSubsets.R")

```

```{r}
all2012 = regsubsets(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2012, nbest = 2, nvmax = 25)

ShowSubsetsTable = ShowSubsets(all2012)
head(arrange(ShowSubsetsTable, Cp))

```

```{r}
Full2012 = lm(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2012)
MSE = (summary(Full2012)$sigma)^2
step(Full2012, scale=MSE, trace = FALSE)
```

```{r}
none2012 = lm(ScoreDiff~1, data=NFLDATA2012)
step(none2012, scope=list(upper=Full2012), scale=MSE, direction="forward", trace = FALSE)
```

```{r}
step(none2012, scope=list(upper=Full2012), scale=MSE, trace = FALSE)
```

```{r}
summary(Full2012)
```

```{r}
plot(Full2012)
```

```{r}
plot(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2012)
```


```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted html

library(readr)
library(mosaic)
library(car)
library(leaps)
library(dplyr)


NFLDATA2013 <- read_csv("NFLDATA2013.csv")
source("ShowSubsets.R")

```

```{r}
all2013 = regsubsets(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2013, nbest = 2, nvmax = 25)

ShowSubsetsTable = ShowSubsets(all2013)
head(arrange(ShowSubsetsTable, Cp))

```

```{r}
Full2013 = lm(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2013)
MSE = (summary(Full2013)$sigma)^2
step(Full2013, scale=MSE, trace = FALSE)
```

```{r}
none2013 = lm(ScoreDiff~1, data=NFLDATA2013)
step(none2013, scope=list(upper=Full2013), scale=MSE, direction="forward", trace = FALSE)
```

```{r}
step(none2013, scope=list(upper=Full2013), scale=MSE, trace = FALSE)
```

```{r}
summary(Full2013)
```

```{r}
plot(Full2013)
```

```{r}
plot(ScoreDiff~FirstDownDiff+RushAttDiff+RushYdsDiff+PassAttDiff+PassCompDiff+PassYdsDiff+PassIntDiff+FumblesDiff+SackYdsDiff+PenYdsDiff+ThirdDownPctDiff+TimePossDiff, data = NFLDATA2013)
```













